"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { MoneyInput } from "@/components/money-input";
import { calculateActualSummary, calculateFinancialSummary, formatMoney } from "@/lib/financial-calculations";
import { useFinancialProfile } from "@/components/financial-provider";
import { EmptyState, PlaceholderValue, SectionCard, SetupCard } from "@/components/application-ui";
import type { SavingsGoal } from "@/lib/financial-types";

function LoadingPlan() { return <p className="loading-copy" aria-live="polite">Loading your financial data…</p>; }
function EditPlan({ step = "review", children = "Edit your plan" }: { step?: string; children?: React.ReactNode }) { return <Link className="card-link" href={`/onboarding?step=${step}`}>{children}<span aria-hidden="true">↗</span></Link>; }

export function DashboardView() {
  const { profile, ready, issue } = useFinancialProfile();
  if (!ready) return <LoadingPlan />;
  if (issue) return <SetupCard title="Your saved plan needs attention">{issue}</SetupCard>;
  if (!profile?.onboarding.completed) return <DashboardSetup />;
  const summary = calculateFinancialSummary(profile);
  if (profile.transactions.length) return <ActualDashboard profile={profile} />;
  const allocation = summary.remainingToAllocate > 0 ? "This amount has not been assigned to your budget or savings yet." : summary.remainingToAllocate === 0 ? "Your plan is fully allocated for this month." : "Your plan is a little higher than your expected income. You can adjust it anytime.";
  return <>
    <section className="monthly-position"><div><p className="app-eyebrow">This month’s plan</p><h2>Here is the shape of your month.</h2><p>These are planning figures based on what you told AWN. They are not bank balances or received income.</p><p className={`allocation-message ${summary.remainingToAllocate < 0 ? "is-warning" : ""}`} role={summary.remainingToAllocate < 0 ? "status" : undefined}>{allocation}</p></div><div className="position-values"><PlaceholderValue label="Expected monthly income">{formatMoney(summary.expectedIncome, profile.currency)}</PlaceholderValue><PlaceholderValue label="Available after planned savings">{formatMoney(summary.plannedAvailable, profile.currency)}</PlaceholderValue><PlaceholderValue label="Remaining to allocate">{formatMoney(summary.remainingToAllocate, profile.currency)}</PlaceholderValue></div></section>
    <div className="app-card-grid"><SectionCard title="Your monthly plan" className="summary-card"><div className="summary-list"><span>Spending limits <strong>{formatMoney(summary.spendingBudget, profile.currency)}</strong></span><span>Planned savings <strong>{formatMoney(summary.plannedSavings, profile.currency)}</strong></span><span>Expected income <strong>{formatMoney(summary.expectedIncome, profile.currency)}</strong></span></div><EditPlan>Review your plan</EditPlan></SectionCard><SectionCard title="Savings goals"><GoalList /></SectionCard></div>
    {(profile.accounts.length > 0 || profile.creditCards.length > 0) && <div className="app-card-grid"><SectionCard title="Accounts"><p className="section-note">Starting account cash</p><strong className="large-value">{formatMoney(summary.accountCash, profile.currency)}</strong><EditPlan step="accounts">Edit accounts</EditPlan></SectionCard><SectionCard title="Credit cards">{profile.creditCards.length ? <div className="summary-list">{summary.availableCredit.map((card) => <span key={card.id}>{card.name}<strong>{formatMoney(card.amount, profile.currency)} available</strong></span>)}</div> : <p className="section-note">No credit cards added.</p>}<EditPlan step="accounts">Edit cards</EditPlan></SectionCard></div>}
    <EmptyState title="Recent activity" href="/transactions" action="View transactions">There is no activity to review yet. Add transaction and bank SMS import are coming soon.</EmptyState>
    <LocalDataPanel />
  </>;
}

function ActualDashboard({ profile }: { profile: NonNullable<ReturnType<typeof useFinancialProfile>["profile"]> }) { const month = new Date().toLocaleDateString("en-CA").slice(0, 7); const actual = calculateActualSummary(profile, month); return <><section className="monthly-position"><div><p className="app-eyebrow">Actual activity · {month}</p><h2>{formatMoney(actual.moneyLeft, profile.currency)} money left this month.</h2><p>Income received minus expenses recorded this month. This is not current account cash or available credit.</p><p className={`allocation-message ${actual.moneyLeft < 0 ? "is-warning" : ""}`}>{actual.moneyLeft < 0 ? "You’ve recorded more expenses than income this month. Take a look when you’re ready—your plan can always be adjusted." : "Your recorded activity is up to date for this month."}</p></div><div className="position-values"><PlaceholderValue label="Income received">{formatMoney(actual.income, profile.currency)}</PlaceholderValue><PlaceholderValue label="Expenses recorded">{formatMoney(actual.expenses, profile.currency)}</PlaceholderValue><PlaceholderValue label="Money left this month">{formatMoney(actual.moneyLeft, profile.currency)}</PlaceholderValue></div></section><div className="app-card-grid"><SectionCard title="Category progress"><div className="summary-list">{profile.categoryBudgets.map((category) => <span key={category.id}>{category.name}<strong>{formatMoney(actual.categorySpending[category.name] ?? 0, profile.currency)} / {formatMoney(category.limit, profile.currency)}</strong></span>)}</div><Link className="card-link" href="/transactions">Review activity <span aria-hidden="true">↗</span></Link></SectionCard><SectionCard title="Your plan"><div className="summary-list"><span>Expected income<strong>{formatMoney(calculateFinancialSummary(profile).expectedIncome, profile.currency)}</strong></span><span>Planned savings<strong>{formatMoney(calculateFinancialSummary(profile).plannedSavings, profile.currency)}</strong></span></div><EditPlan>Review your plan</EditPlan></SectionCard></div></>; }

function DashboardSetup() { return <><section className="monthly-position"><div><p className="app-eyebrow">Your monthly picture</p><h2>Let’s build a plan that works for you.</h2><p>Start with what you expect to earn and how you would like to use it. You can change it whenever you need to.</p><Link className="app-button app-button-light" href="/onboarding">Continue your setup <span aria-hidden="true">↗</span></Link></div><div className="position-values"><PlaceholderValue label="Expected income">—</PlaceholderValue><PlaceholderValue label="Spending limits">—</PlaceholderValue><PlaceholderValue label="Planned savings">—</PlaceholderValue></div></section><div className="app-card-grid"><SetupCard eyebrow="Your starting plan" title="Take it one small step at a time">Your information is saved securely to your AWN Household as you continue. You can add accounts and savings goals later.</SetupCard><EmptyState title="Recent activity">There is no activity to review yet. Manual entry and SMS import will live here later.</EmptyState></div></>; }

function GoalList() { const { profile } = useFinancialProfile(); const [editing, setEditing] = useState<SavingsGoal>(); if (!profile?.savingsGoals.length) return <><p className="section-note">No savings goals yet. You can add one whenever it feels useful.</p><EditPlan step="savings">Add a savings goal</EditPlan></>; return <>{editing && <SavingsProgressEditor goal={editing} close={() => setEditing(undefined)} />}<div className="goal-list">{[...profile.savingsGoals].sort((a, b) => a.priority - b.priority).map((goal) => <div key={goal.id}><span>{goal.name}<small>{formatMoney(goal.saved, profile.currency)} saved of {formatMoney(goal.target, profile.currency)}</small></span><strong>{formatMoney(goal.contribution, profile.currency)} / month</strong><button type="button" className="text-button" onClick={() => setEditing(goal)} aria-label={`Update saved amount for ${goal.name}`}>Update progress</button></div>)}<EditPlan step="savings">Edit savings goals</EditPlan></div></>; }

function SavingsProgressEditor({ goal, close }: { goal: SavingsGoal; close: () => void }) { const { profile, save } = useFinancialProfile(); const [saved, setSaved] = useState(goal.saved); const [error, setError] = useState(""); const dialogRef = useRef<HTMLDivElement>(null); useEffect(() => { dialogRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [close]); if (!profile) return null; const submit = async () => { if (saved < 0 || saved > goal.target) return setError(`Enter an amount between ${formatMoney(0, profile.currency)} and ${formatMoney(goal.target, profile.currency)}.`); const updated = profile.savingsGoals.map((item) => item.id === goal.id ? { ...item, saved } : item); if (await save({ ...profile, savingsGoals: updated })) close(); }; return <div className="dialog-backdrop"><div className="confirm-dialog savings-editor" role="dialog" aria-modal="true" aria-labelledby="savings-progress-title" tabIndex={-1} ref={dialogRef}><h2 id="savings-progress-title">Update {goal.name}</h2><p>Updating this changes your goal progress only. It won’t change your account balance or monthly activity.</p><label className="form-field">Amount already saved<MoneyInput value={saved} onValueChange={setSaved} aria-invalid={!!error} aria-describedby={error ? "savings-progress-error" : undefined} /></label>{error && <p id="savings-progress-error" className="form-message is-error" role="alert">{error}</p>}<div className="confirm-dialog-actions"><button type="button" className="app-button app-button-secondary" onClick={close}>Cancel</button><button type="button" className="app-button" onClick={submit}>Save progress</button></div></div></div>; }

export function AccountsView() { const { profile, ready, issue } = useFinancialProfile(); if (!ready) return <LoadingPlan />; if (issue) return <SetupCard title="Your saved plan needs attention">{issue}</SetupCard>; const actual = profile ? calculateActualSummary(profile, new Date().toLocaleDateString("en-CA").slice(0, 7)) : null; return <div className="account-sections"><section><div className="section-label"><span aria-hidden="true">◒</span><div><p className="app-eyebrow">Accounts</p><h2>Where your money lives</h2></div></div>{profile?.accounts.length ? <div className="financial-item-list">{profile.accounts.map((account) => <article key={account.id}><span>{account.name}<small>{account.type} · Opening {formatMoney(account.balance, profile.currency)}</small></span><strong>{formatMoney(actual?.accounts[account.id] ?? account.balance, profile.currency)} current</strong></article>)}<p className="section-note">Current balances are derived from opening amounts and recorded activity.</p><EditPlan step="accounts">Edit setup</EditPlan></div> : <SetupCard title="No accounts added">You can add accounts later. Use friendly names and summary balances only.</SetupCard>}</section><section><div className="section-label"><span aria-hidden="true">◌</span><div><p className="app-eyebrow">Credit cards</p><h2>What you need to pay back</h2></div></div>{profile?.creditCards.length ? <div className="financial-item-list">{profile.creditCards.map((card) => <article key={card.id}><span>{card.name}<small>Opening owed {formatMoney(card.owed, profile.currency)}</small></span><strong>{formatMoney(actual?.cards[card.id] ?? card.owed, profile.currency)} owed<br />{formatMoney(actual?.availableCredit[card.id] ?? card.limit - card.owed, profile.currency)} available</strong></article>)}<EditPlan step="accounts">Edit setup</EditPlan></div> : <SetupCard title="No credit cards added">Cards stay separate from cash, so your plan stays easier to understand.</SetupCard>}</section></div>; }

export function PlanView() { const { profile, ready, issue } = useFinancialProfile(); if (!ready) return <LoadingPlan />; if (issue) return <SetupCard title="Your saved plan needs attention">{issue}</SetupCard>; if (!profile?.onboarding.completed) return <SetupCard title="Your plan will take shape here">Finish your starting plan to see your chosen spending limits and savings goals together.</SetupCard>; const summary = calculateFinancialSummary(profile); return <><div className="app-card-grid"><SectionCard title="Monthly budget"><div className="summary-list">{profile.categoryBudgets.map((category) => <span key={category.id}>{category.name}<strong>{formatMoney(category.limit, profile.currency)}</strong></span>)}</div><p className="section-note">Total monthly budget: {formatMoney(summary.spendingBudget, profile.currency)}</p><EditPlan step="budget">Edit monthly budget</EditPlan></SectionCard><SectionCard title="Savings goals"><GoalList /></SectionCard></div><SetupCard eyebrow="Upcoming commitments" title="A place for what is already spoken for">Recurring commitments are coming soon. AWN will not invent a schedule before you add one.</SetupCard></>; }

export function LocalDataPanel() { return <section className="local-data"><div><p className="app-eyebrow">AWN Cloud</p><h2>Your plan follows your account.</h2><p>Your financial data is saved to your personal Household and is available when you sign in from another browser or device.</p></div></section>; }
