"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { cloneElement, isValidElement, useEffect, useId, useRef, useState, type ReactElement } from "react";
import { calculateFinancialSummary, formatMoney, moneyInput, parseMoney } from "@/lib/financial-calculations";
import { currencies, createFinancialProfile, newLocalId, type Account, type CreditCard, type FinancialProfile, type IncomeSource, type SavingsGoal } from "@/lib/financial-types";
import { useFinancialProfile } from "@/components/financial-provider";
import { hasLinkedAccountActivity, hasLinkedCardActivity, removalGuardMessage } from "@/lib/financial-reference-guards";

const stepNames = ["Currency & income", "Accounts & cards", "Category budgets", "Savings goals", "Review & confirm"];
const suggestedCategories = ["Housing", "Utilities", "Groceries", "Transport", "Dining", "Shopping", "Health", "Entertainment", "Family", "Other"];
type Errors = Record<string, string>;

const updateAt = <T extends { id: string }>(items: T[], id: string, patch: Partial<T>) => items.map((item) => item.id === id ? { ...item, ...patch } : item);
const removeAt = <T extends { id: string }>(items: T[], id: string) => items.filter((item) => item.id !== id);
const incomeItem = (): IncomeSource => ({ id: newLocalId(), name: "", amount: 0, day: 1 });
const accountItem = (): Account => ({ id: newLocalId(), name: "", type: "current", balance: 0 });
const cardItem = (): CreditCard => ({ id: newLocalId(), name: "", limit: 0, owed: 0, dueDay: 1 });
const goalItem = (): SavingsGoal => ({ id: newLocalId(), name: "", target: 0, saved: 0, contribution: 0, priority: 1 });

export function OnboardingFlow() {
  const router = useRouter(); const { profile, ready, issue, save } = useFinancialProfile();
  const [draft, setDraft] = useState<FinancialProfile | null>(null); const [step, setStep] = useState(1); const [errors, setErrors] = useState<Errors>({}); const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false); const heading = useRef<HTMLHeadingElement>(null); const errorBox = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!ready || draft) return; queueMicrotask(() => { const existing = profile ?? createFinancialProfile(); const params = new URLSearchParams(window.location.search); const names = ["income", "accounts", "budget", "savings", "review"]; const requested = names.indexOf(params.get("step") ?? "") + 1; setDraft(existing); setStep(requested || existing.onboarding.currentStep || 1); }); }, [ready, profile, draft]);
  useEffect(() => { if (draft) save({ ...draft, onboarding: { ...draft.onboarding, currentStep: step } }); }, [draft, step, save]);
  useEffect(() => { heading.current?.focus(); }, [step]);
  if (!ready || !draft) return <main className="onboarding-page"><p className="loading-copy">Loading your local plan…</p></main>;
  if (issue) return <main className="onboarding-page"><section className="onboarding-card"><h1>Your saved plan needs attention.</h1><p>{issue}</p><Link className="app-button app-button-light" href="/dashboard">Return to dashboard</Link></section></main>;
  const change = (patch: Partial<FinancialProfile>) => setDraft((current) => current ? { ...current, ...patch } : current);
  const go = (next: number) => { setErrors({}); setNotice(""); setStep(next); };
  const validate = () => { const next: Errors = {}; if (step === 1) { if (!draft.incomeSources.length) next.income = "Add at least one expected monthly income source."; draft.incomeSources.forEach((item) => { if (!item.name.trim()) next[`income-${item.id}-name`] = "Add a name for this income source."; if (item.amount <= 0) next[`income-${item.id}-amount`] = "Enter an amount above zero."; if (!Number.isInteger(item.day) || item.day < 1 || item.day > 31) next[`income-${item.id}-day`] = "Use a day from 1 to 31."; }); } if (step === 2) { draft.accounts.forEach((item) => { if (!item.name.trim()) next[`account-${item.id}-name`] = "Add a friendly account name."; if (item.balance < 0) next[`account-${item.id}-balance`] = "Starting balance cannot be negative."; }); draft.creditCards.forEach((item) => { if (!item.name.trim()) next[`card-${item.id}-name`] = "Add a friendly card name."; if (item.limit < 0) next[`card-${item.id}-limit`] = "Credit limit cannot be negative."; if (item.owed < 0) next[`card-${item.id}-owed`] = "Balance owed cannot be negative."; if (item.owed > item.limit) next[`card-${item.id}-owed`] = "Balance owed is higher than this card’s limit. Check the amounts."; if (!Number.isInteger(item.dueDay) || item.dueDay < 1 || item.dueDay > 31) next[`card-${item.id}-day`] = "Use a day from 1 to 31."; }); } if (step === 3) { if (!draft.categoryBudgets.length) next.category = "Choose at least one category for your monthly plan."; const seen = new Set<string>(); draft.categoryBudgets.forEach((item) => { const name = item.name.trim().toLowerCase(); if (!name) next[`category-${item.id}-name`] = "Add a category name."; if (seen.has(name)) next[`category-${item.id}-name`] = "Use each category only once."; seen.add(name); if (item.limit <= 0) next[`category-${item.id}-limit`] = "Enter a monthly limit above zero."; }); } if (step === 4) draft.savingsGoals.forEach((item) => { if (!item.name.trim()) next[`goal-${item.id}-name`] = "Add a goal name."; if (item.target <= 0) next[`goal-${item.id}-target`] = "Enter a target above zero."; if (item.saved < 0 || item.saved > item.target) next[`goal-${item.id}-saved`] = "Saved amount must be between zero and the target."; if (item.contribution < 0) next[`goal-${item.id}-contribution`] = "Contribution cannot be negative."; if (item.targetDate && Number.isNaN(Date.parse(item.targetDate))) next[`goal-${item.id}-date`] = "Use a valid target date."; }); setErrors(next); if (Object.keys(next).length) requestAnimationFrame(() => errorBox.current?.focus()); return !Object.keys(next).length; };
  const continueStep = () => { if (!validate()) return; if (step < 5) go(step + 1); };
  const complete = () => { if (submitting || !validate()) return; setSubmitting(true); const completed = { ...draft, onboarding: { currentStep: 5, completed: true } }; if (save(completed)) router.push("/dashboard"); else setSubmitting(false); };
  const hasAmounts = draft.incomeSources.some((item) => item.amount > 0) || draft.accounts.some((item) => item.balance !== 0) || draft.creditCards.some((item) => item.limit > 0 || item.owed > 0) || draft.categoryBudgets.some((item) => item.limit > 0) || draft.savingsGoals.some((item) => item.target > 0 || item.saved > 0 || item.contribution > 0);
  return <main className="onboarding-page"><header className="onboarding-header"><Link className="app-wordmark onboarding-brand" href="/" aria-label="Return to AWN homepage"><span className="wordmark-mark" aria-hidden="true">a</span><span>awn</span></Link><Link className="onboarding-back" href="/">Return home</Link></header><section className="onboarding-card"><p className="app-eyebrow">Your starting plan</p><p className="step-status" aria-live="polite">Step {step} of 5: {stepNames[step - 1]}</p><h1 tabIndex={-1} ref={heading}>{stepNames[step - 1]}</h1><p className="onboarding-intro">{step === 1 ? "Let’s start with the income you expect in a typical month." : step === 2 ? "This is optional. Friendly names and summary amounts are enough—never enter card numbers or login details." : step === 3 ? "Choose only the parts of your month that matter to you." : step === 4 ? "This is optional too. A goal can wait until you are ready." : "Take a quiet look at the plan you have made."}</p>{Object.keys(errors).length > 0 && <div className="form-message is-error" role="alert" tabIndex={-1} ref={errorBox}>Please review the highlighted fields. {Object.values(errors)[0]}</div>}{notice && <p className="form-message is-success" role="status">{notice}</p>}
  {step === 1 && <IncomeStep draft={draft} change={change} errors={errors} hasAmounts={hasAmounts} />}{step === 2 && <AccountsStep draft={draft} change={change} errors={errors} />}{step === 3 && <BudgetStep draft={draft} change={change} errors={errors} />}{step === 4 && <SavingsStep draft={draft} change={change} errors={errors} />}{step === 5 && <ReviewStep draft={draft} />}
  <div className="onboarding-actions"><button type="button" className="app-button app-button-secondary" onClick={() => go(step - 1)} disabled={step === 1}>Back</button>{step === 2 || step === 4 ? <button type="button" className="text-button" onClick={() => go(step + 1)}>Skip for now</button> : null}{step < 5 ? <button type="button" className="app-button" onClick={continueStep}>Continue</button> : <button type="button" className="app-button" onClick={complete} disabled={submitting}>{submitting ? "Saving your plan…" : "Confirm and finish"}</button>}</div></section></main>;
}

function Field({ label, error, children, hint }: { label: string; error?: string; hint?: string; children: React.ReactNode }) { const errorId = useId(); const control = isValidElement(children) ? cloneElement(children as ReactElement<{ "aria-invalid"?: boolean; "aria-describedby"?: string }>, { "aria-invalid": !!error, "aria-describedby": error ? errorId : undefined }) : children; return <label className="form-field">{label}{control}{hint && <small>{hint}</small>}{error && <small className="field-error" id={errorId}>{error}</small>}</label>; }
function MoneyField({ label, value, onChange, error }: { label: string; value: number; onChange: (value: number) => void; error?: string }) { return <Field label={label} error={error}><input inputMode="decimal" type="text" value={moneyInput(value)} onChange={(event) => onChange(parseMoney(event.target.value))} placeholder="0.00" /></Field>; }
function GuardedRemoveButton({ linked, kind, label, onRemove }: { linked: boolean; kind: "account" | "credit-card"; label: string; onRemove: () => void }) { const messageId = useId(); return <><button type="button" className="icon-button" aria-label={label} aria-describedby={linked ? messageId : undefined} disabled={linked} onClick={onRemove}>Remove</button>{linked && <p className="form-help removal-guard" id={messageId}>{removalGuardMessage(kind)}</p>}</>; }

function IncomeStep({ draft, change, errors, hasAmounts }: { draft: FinancialProfile; change: (patch: Partial<FinancialProfile>) => void; errors: Errors; hasAmounts: boolean }) { const add = () => change({ incomeSources: [...draft.incomeSources, incomeItem()] }); const set = (id: string, patch: Partial<IncomeSource>) => change({ incomeSources: updateAt(draft.incomeSources, id, patch) }); const currencyError = errors.currency; return <div className="step-content"><Field label="Your base currency" error={currencyError} hint={hasAmounts ? "To keep existing amounts accurate, reset your local plan before choosing another currency." : "This will be used throughout your plan."}><select value={draft.currency} onChange={(event) => { if (hasAmounts && event.target.value !== draft.currency) return; change({ currency: event.target.value as FinancialProfile["currency"] }); }} disabled={hasAmounts}>{currencies.map((currency) => <option key={currency}>{currency}</option>)}</select></Field><div className="editor-heading"><h2>Expected monthly income</h2><button type="button" className="text-button" onClick={add}>Add income source</button></div>{errors.income && <p className="field-error">{errors.income}</p>}<div className="repeat-list">{draft.incomeSources.map((source, index) => <article className="repeat-card" key={source.id}><div className="repeat-card-heading"><h3>Income source {index + 1}</h3><button type="button" className="icon-button" onClick={() => change({ incomeSources: removeAt(draft.incomeSources, source.id) })} aria-label={`Remove ${source.name || `income source ${index + 1}`}`}>Remove</button></div><Field label="Name" error={errors[`income-${source.id}-name`]}><input value={source.name} onChange={(event) => set(source.id, { name: event.target.value })} placeholder="e.g. Main work" /></Field><div className="field-row"><MoneyField label="Expected monthly amount" value={source.amount} onChange={(amount) => set(source.id, { amount })} error={errors[`income-${source.id}-amount`]} /><Field label="Expected day" error={errors[`income-${source.id}-day`]} hint="31 means the final day in shorter months."><input type="number" min="1" max="31" value={source.day} onChange={(event) => set(source.id, { day: Number(event.target.value) })} /></Field></div></article>)}</div>{!draft.incomeSources.length && <button type="button" className="add-card" onClick={add}>Add your expected monthly income</button>}</div>; }

function AccountsStep({ draft, change, errors }: { draft: FinancialProfile; change: (patch: Partial<FinancialProfile>) => void; errors: Errors }) {
  const setAccount = (id: string, patch: Partial<Account>) => change({ accounts: updateAt(draft.accounts, id, patch) });
  const setCard = (id: string, patch: Partial<CreditCard>) => change({ creditCards: updateAt(draft.creditCards, id, patch) });
  return <div className="step-content"><div className="editor-heading"><h2>Accounts</h2><button type="button" className="text-button" onClick={() => change({ accounts: [...draft.accounts, accountItem()] })}>Add account</button></div><p className="form-help">Enter only a friendly name and a starting balance. AWN does not need account numbers, card numbers, CVVs, PINs, or login details.</p>{draft.accounts.map((account, index) => <article className="repeat-card" key={account.id}><div className="repeat-card-heading"><h3>Account {index + 1}</h3><GuardedRemoveButton linked={hasLinkedAccountActivity(draft, account.id)} kind="account" label={`Remove ${account.name || `account ${index + 1}`}`} onRemove={() => change({ accounts: removeAt(draft.accounts, account.id) })} /></div><Field label="Account name" error={errors[`account-${account.id}-name`]}><input value={account.name} onChange={(event) => setAccount(account.id, { name: event.target.value })} placeholder="e.g. Everyday account" /></Field><div className="field-row"><Field label="Type"><select value={account.type} onChange={(event) => setAccount(account.id, { type: event.target.value as Account["type"] })}><option value="current">Current</option><option value="savings">Savings</option><option value="cash">Cash</option></select></Field><MoneyField label="Starting balance" value={account.balance} onChange={(balance) => setAccount(account.id, { balance })} error={errors[`account-${account.id}-balance`]} /></div></article>)}<div className="editor-heading"><h2>Credit cards</h2><button type="button" className="text-button" onClick={() => change({ creditCards: [...draft.creditCards, cardItem()] })}>Add credit card</button></div>{draft.creditCards.map((card, index) => <article className="repeat-card" key={card.id}><div className="repeat-card-heading"><h3>Credit card {index + 1}</h3><GuardedRemoveButton linked={hasLinkedCardActivity(draft, card.id)} kind="credit-card" label={`Remove ${card.name || `credit card ${index + 1}`}`} onRemove={() => change({ creditCards: removeAt(draft.creditCards, card.id) })} /></div><Field label="Card name" error={errors[`card-${card.id}-name`]}><input value={card.name} onChange={(event) => setCard(card.id, { name: event.target.value })} placeholder="e.g. Travel card" /></Field><div className="field-row"><MoneyField label="Credit limit" value={card.limit} onChange={(limit) => setCard(card.id, { limit })} error={errors[`card-${card.id}-limit`]} /><MoneyField label="Current balance owed" value={card.owed} onChange={(owed) => setCard(card.id, { owed })} error={errors[`card-${card.id}-owed`]} /><Field label="Payment due day" error={errors[`card-${card.id}-day`]}><input type="number" min="1" max="31" value={card.dueDay} onChange={(event) => setCard(card.id, { dueDay: Number(event.target.value) })} /></Field></div></article>)}</div>;
}

function BudgetStep({ draft, change, errors }: { draft: FinancialProfile; change: (patch: Partial<FinancialProfile>) => void; errors: Errors }) { const [choice, setChoice] = useState(suggestedCategories[0]); const [custom, setCustom] = useState(""); const add = (name: string) => { const cleaned = name.trim(); if (!cleaned || draft.categoryBudgets.some((category) => category.name.trim().toLowerCase() === cleaned.toLowerCase())) return; change({ categoryBudgets: [...draft.categoryBudgets, { id: newLocalId(), name: cleaned, limit: 0 }] }); setCustom(""); }; return <div className="step-content"><div className="category-picker"><select value={choice} onChange={(event) => setChoice(event.target.value)}>{suggestedCategories.map((category) => <option key={category}>{category}</option>)}</select><button type="button" className="app-button" onClick={() => add(choice)}>Add category</button></div><div className="custom-category"><Field label="Or add your own category"><input value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="e.g. Pets" /></Field><button type="button" className="text-button" onClick={() => add(custom)}>Add custom category</button></div>{errors.category && <p className="field-error">{errors.category}</p>}<div className="repeat-list">{draft.categoryBudgets.map((category, index) => <article className="repeat-card compact-card" key={category.id}><div className="repeat-card-heading"><h3>Category {index + 1}</h3><button type="button" className="icon-button" aria-label={`Remove ${category.name || `category ${index + 1}`}`} onClick={() => change({ categoryBudgets: removeAt(draft.categoryBudgets, category.id) })}>Remove</button></div><div className="field-row"><Field label="Category name" error={errors[`category-${category.id}-name`]}><input value={category.name} onChange={(event) => change({ categoryBudgets: updateAt(draft.categoryBudgets, category.id, { name: event.target.value }) })} /></Field><MoneyField label="Monthly limit" value={category.limit} onChange={(limit) => change({ categoryBudgets: updateAt(draft.categoryBudgets, category.id, { limit }) })} error={errors[`category-${category.id}-limit`]} /></div></article>)}</div></div>; }

function SavingsStep({ draft, change, errors }: { draft: FinancialProfile; change: (patch: Partial<FinancialProfile>) => void; errors: Errors }) { const set = (id: string, patch: Partial<SavingsGoal>) => change({ savingsGoals: updateAt(draft.savingsGoals, id, patch) }); return <div className="step-content"><div className="editor-heading"><h2>Savings goals</h2><button type="button" className="text-button" onClick={() => change({ savingsGoals: [...draft.savingsGoals, { ...goalItem(), priority: draft.savingsGoals.length + 1 }] })}>Add savings goal</button></div>{draft.savingsGoals.map((goal, index) => <article className="repeat-card" key={goal.id}><div className="repeat-card-heading"><h3>Goal {index + 1}</h3><button type="button" className="icon-button" aria-label={`Remove ${goal.name || `goal ${index + 1}`}`} onClick={() => change({ savingsGoals: removeAt(draft.savingsGoals, goal.id) })}>Remove</button></div><Field label="Goal name" error={errors[`goal-${goal.id}-name`]}><input value={goal.name} onChange={(event) => set(goal.id, { name: event.target.value })} placeholder="e.g. Home fund" /></Field><div className="field-row three"><MoneyField label="Target amount" value={goal.target} onChange={(target) => set(goal.id, { target })} error={errors[`goal-${goal.id}-target`]} /><MoneyField label="Already saved" value={goal.saved} onChange={(saved) => set(goal.id, { saved })} error={errors[`goal-${goal.id}-saved`]} /><MoneyField label="Planned monthly contribution" value={goal.contribution} onChange={(contribution) => set(goal.id, { contribution })} error={errors[`goal-${goal.id}-contribution`]} /></div><div className="field-row"><Field label="Target date (optional)" error={errors[`goal-${goal.id}-date`]}><input type="date" value={goal.targetDate ?? ""} onChange={(event) => set(goal.id, { targetDate: event.target.value || undefined })} /></Field><Field label="Priority"><select value={goal.priority} onChange={(event) => set(goal.id, { priority: Number(event.target.value) })}><option value="1">First</option><option value="2">Next</option><option value="3">Later</option></select></Field></div></article>)}</div>; }

function ReviewStep({ draft }: { draft: FinancialProfile }) { const summary = calculateFinancialSummary(draft); const message = summary.remainingToAllocate < 0 ? "Your plan is a little higher than your expected income. You can still save it and adjust it anytime." : summary.remainingToAllocate === 0 ? "Your plan is fully allocated. You’re off to a good start." : "This amount has not been assigned to your budget or savings yet."; return <div className="step-content"><div className="review-summary"><span>Expected monthly income <strong>{formatMoney(summary.expectedIncome, draft.currency)}</strong></span><span>Monthly spending budget <strong>{formatMoney(summary.spendingBudget, draft.currency)}</strong></span><span>Planned monthly savings <strong>{formatMoney(summary.plannedSavings, draft.currency)}</strong></span><span>Available after planned savings <strong>{formatMoney(summary.plannedAvailable, draft.currency)}</strong></span><span>Remaining to allocate <strong>{formatMoney(summary.remainingToAllocate, draft.currency)}</strong></span></div><p className={`form-message ${summary.remainingToAllocate < 0 ? "is-warning" : "is-success"}`} role="status">{message}</p><p className="privacy-note">Your information stays in this browser for now. It is not sent to an AWN server or synced across devices.</p></div>; }
